name: Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: latest
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn
          cache-dependency-path: "**/yarn.lock"
      - name: Install dependencies
        run: yarn
      - name: run tests
        run: yarn test
      - name: check if diff
        run: git diff --exit-code || exit 1
